# Generated by Django 3.0.6 on 2021-12-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0002_auto_20211203_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Cinema',
        ),
        migrations.DeleteModel(
            name='Screening',
        ),
    ]
